image: registry.affilyx.com/images/laravel:tests-1.3.5

stages:
  - install
  - test

cache:
  key: "$CI_COMMIT_REF_SLUG-vendor"
  paths:
    - vendor/

composer:
  stage: install
  script:
    - composer install --no-interaction --prefer-dist
  cache:
    key: "$CI_COMMIT_REF_SLUG-vendor"
    paths:
      - vendor/

phpunit:
  stage: test
  script:
    - vendor/bin/phpunit --colors=never
  cache:
    key: "$CI_COMMIT_REF_SLUG-vendor"
    policy: pull
    paths:
      - vendor/

phpstan:
  stage: test
  script:
    - php -d memory_limit=512M vendor/bin/phpstan analyse
  cache:
    key: "$CI_COMMIT_REF_SLUG-vendor"
    policy: pull
    paths:
      - vendor/

pint:
  stage: test
  script:
    - vendor/bin/pint --test
  cache:
    key: "$CI_COMMIT_REF_SLUG-vendor"
    policy: pull
    paths:
      - vendor/
